version: '3.9'
services:
  app:
    build:
      context: .
    ports:
      - "3000:3000"
    volumes:
      # Mount the current directory to /app inside the container
      - .:/app
      # Ensure node_modules are handled correctly to avoid conflicts
      - /app/node_modules
    command: npm run dev
